---
title: "About"
author: "Darren Irwin"
---

I am a Professor of Zoology at the University of British Columbia, where I have the great fortune to work with a wonderful group of students. To learn more about our research, go to: <https://www.zoology.ubc.ca/~irwin/irwinlab/> 

Disclaimer: I am mostly self-taught in the area of computer science and programming, so you will likely find better sources to learn about those topics. My goal here is to help other biologists learn to start programming. I have chosen the Julia language because of its easy entry, its speed and memory efficiency, and because it has been hugely useful in my own research.

Thanks: I have benefitted greatly from many excellent courses available from organizations such as Compute Canada, the Digital Alliance of Canada, and UBC Advanced Research Computing. I also thank the many YouTubers, bloggers, and book authors who provide excellent information about Julia and other languages. And of course I thank the inventors of Julia (you can learn more at <https://en.wikipedia.org/wiki/Julia_(programming_language)>).  


This whole website was generated using Quarto, which allows embedding of runnable Julia code.

To learn more about Quarto websites visit <https://quarto.org/docs/websites>.
