---
title: "Download and Install Julia"
author: "Darren Irwin"
execute:
  echo: true
format:
  html:
    code-fold: false
engine: julia
---

To download and install Julia, go to this URL and follow instructions: <https://julialang.org/install/>

That website will likely detect your operating system and suggest the right approach.

**If you have a Mac:** The above will direct you to simply open a Terminal window (look for the Terminal application in your `Applications/Utilities` directory) and type the command below at the Terminal prompt:

`curl -fsSL https://install.julialang.org | sh`

**If you have a PC:** The above [Julia install website](https://julialang.org/install/) will give you two approaches to installing Julia using downloadable installers. For the second of these, there is a way to do this using a command-line interface window (using e.g., Windows Powershell or Windows Terminal), by typing the command below at the prompt:

`winget install --name Julia --id 9NJNWW8PVKMN -e -s msstore`

The above commands (whether Mac or PC) install the Juliaup installation manager, which is a wonderful tool to help update Julia and keep different versions (if you wish) available on your computer.

::: {.callout-note}
## If desired: update Julia 
If you already have Julia and Juliaup installed, and you want to update Julia to the latest available stable version, enter the command `juliaup update` into your Terminal or other command-line interface. (You can see other useful Juliaup commands [here](https://github.com/JuliaLang/juliaup))
:::

### Now, run Julia!

In the Terminal window, type `julia` at the prompt. After some time (only the first time you do this), you should see a julia logo and a prompt saying `julia>` . This means Julia is installed and running.

Try typing a simple calculation, e.g. `1 + 3` then Enter or Return, and see what happens.

Now try entering `"Hello World"` (make sure you put the quotes).

New try entering `print("Hello World")` (make sure you put the parentheses and quotes).

Notice the subtle difference in how Julia evaluates those expressions?

With the above, you are using the REPL, the Read-Evaluate-Print-Loop. This is a common way of running Julia. (Another way is to save scripts and execute them, but that is usually for more advanced use.)

Now, go to the next page to learn (using arrow at lower right of this page) more about interacting with Julia.

